# Generated by Django 5.2.6 on 2026-04-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='profiles_gender_3ecb8a_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['age_group'], name='profiles_age_gro_af31b0_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country_id'], name='profiles_country_d0a8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['age'], name='profiles_age_145029_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_at'], name='profiles_created_cbafd1_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender_probability'], name='profiles_gender__98ea1a_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country_probability'], name='profiles_country_584d3f_idx'),
        ),
    ]
