# Generated by Django 5.2.6 on 2026-05-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_country_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_age_gro_af31b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_gender__98ea1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_country_584d3f_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender', 'age'], name='profiles_gender_726dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country_id', 'age'], name='profiles_country_838350_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country_id', 'gender'], name='profiles_country_f84d1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(condition=models.Q(('age__gte', 0)), name='age_non_negative'),
        ),
    ]
